addSbtPlugin("org.scoverage"      % "sbt-scoverage"   % "2.4.4")
addSbtPlugin("io.stryker-mutator" % "sbt-stryker4s"   % "1.1.1")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"    % "2.6.2")
addSbtPlugin("com.github.sbt"     % "sbt-pgp"         % "2.3.2")
addSbtPlugin("com.typesafe"       % "sbt-mima-plugin" % "1.2.1")
addSbtPlugin("ch.epfl.scala"      % "sbt-tasty-mima"  % "1.4.0")
